### ISSUE TITLE
Account Signature

### ISSUE THREAD

**Issue by lootag** [paul-schaaf/solana-escrow#1]
Hi :-) 
first off, thanks for the wonderful work, your code and blog post helped out a bunch. 
There's just one thing that is not entirely clear: in your code you don't check whether the signature is valid. Is it that you forgot about it, or is it because the Solana runtime checks it automatically?
Thanks a lot!

**Comment by paul-schaaf** [comment]
hi @lootag ! I'm glad it's useful to you.

https://github.com/paul-schaaf/solana-escrow/blob/531b794ffd31839e38bdb38bd1510adb095777fb/src/processor.rs#L45
https://github.com/paul-schaaf/solana-escrow/blob/531b794ffd31839e38bdb38bd1510adb095777fb/src/processor.rs#L108

These two lines check that `is_signer` is true on a given account. The runtime will only set this property to true if the tx is signed by that account so in your program just checking whether `is_signer == true` is enough.

**Comment by lootag** [comment]
That's precisely what I wanted to know 😃
Thanks again!
